### PR TITLE
Fixing the RdfEntityType creation.

### LINKED ISSUE #24: Cannot create new bundle
When trying to create a new bundle, the following exception is thrown:

```
The website encountered an unexpected error. Please try again later.
TypeError: Argument 2 passed to Drupal\rdf_entity\Entity\RdfEntityMapping::loadByName() must be of the type string, null given, called in modules/contrib/rdf_entity/rdf_entity.module on line 203 in Drupal\rdf_entity\Entity\RdfEntityMapping::loadByName() (line 271 of modules/contrib/rdf_entity/src/Entity/RdfEntityMapping.php).

Drupal\rdf_entity\Entity\RdfEntityMapping::loadByName('rdf_entity', NULL) (Line: 203)
rdf_entity_form_alter(Array, Object, 'rdf_type_form') (Line: 501)
Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'rdf_type_form') (Line: 830)
Drupal\Core\Form\FormBuilder->prepareForm('rdf_type_form', Array, Object) (Line: 272)
Drupal\Core\Form\FormBuilder->buildForm('rdf_type_form', Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 153)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

```

This is because in `rdf_entity_form_alter` we are trying to load an rdf entity mapping object even if the bundle is now being created.

This is easy to fix by checking if the entity is new.

### PR DESCRIPTION
**Pull request by upchuk**
This fixes GH-24.

### CODE REVIEW

File: tests/src/Functional/RdfEntityTypeCreation.php [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+namespace Drupal\Tests\rdf_entity\Functional;
+
+use Drupal\Tests\BrowserTestBase;
+
+/**
+ * Tests the creation of RdfEntityType entities (RDF bundles)
+ *
+ * @group rdf_entity
+ */
+class RdfEntityTypeCreation extends BrowserTestBase {
```
Comment (pfrenssen) [inline tests/src/Functional/RdfEntityTypeCreation.php]: Let's call it `RdfEntityTypeCreationTest` so that it honors the age old traditions of test naming in Drupal.

File: rdf_entity.module [hunk 2]
```diff
@@ -195,18 +198,24 @@ function rdf_entity_form_alter(&$form, FormStateInterface $form_state) {
     '#tree' => TRUE,
   ];
 
-  if (!$mapping = RdfEntityMapping::loadByName($entity_type_id, $bundle_entity->id())) {
-    $mapping = RdfEntityMapping::create([
-      'entity_type_id' => $entity_type_id,
-      'bundle' => $bundle_entity->id(),
-    ]);
+  // When creating a new bundle we can't yet use it for creating a mapping. In
+  // this case we defer to the custom submit handler..
```
Comment (claudiu-cristea) [inline rdf_entity.module]: This is not an error for code sniffer... but still: there are 2 dots at the end of the phrase.

File: tests/src/Functional/RdfEntityTypeCreation.php [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+  /**
+   * {@inheritdoc}
+   */
+  public static $modules = [
+    'rdf_entity',
+    // @todo remove the node dependency after the bug in GH-47 is fixed.
```
Comment (claudiu-cristea) [inline tests/src/Functional/RdfEntityTypeCreation.php]: The related PR is merged. Let's drop this now.

File: tests/src/Functional/RdfEntityTypeCreation.php [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+ * Tests the creation of RdfEntityType entities (RDF bundles)
+ *
+ * @group rdf_entity
+ */
+class RdfEntityTypeCreation extends BrowserTestBase {
+
+  /**
+   * {@inheritdoc}
+   */
+  public static $modules = [
```
Comment (claudiu-cristea) [inline tests/src/Functional/RdfEntityTypeCreation.php]: It's `protected`, no?

**Review by claudiu-cristea — CHANGES_REQUESTED** [review]

File: tests/src/Functional/RdfEntityTypeCreation.php (hunk 4 above)
Comment (upchuk) [reply tests/src/Functional/RdfEntityTypeCreation.php]: @claudiu-cristea No, it's public. At least that is what's in other core tests.

Comment (claudiu-cristea) [reply tests/src/Functional/RdfEntityTypeCreation.php]: @upchuk You should check the parent class property, not other tests. The core is scheduled to correct this in https://www.drupal.org/project/drupal/issues/2822382

Comment (upchuk) [reply tests/src/Functional/RdfEntityTypeCreation.php]: @claudiu-cristea Ah yes, you are right. Thanks!

**Comment by upchuk** [comment]
@claudiu-cristea Pushed the fixes, thanks for the review. Let me know if there is anything else.

**Comment by claudiu-cristea** [comment]
@upchuk For some reasons the test is failing.

**Comment by upchuk** [comment]
@claudiu-cristea Weird, all I did was change the class name to append `Test` to it...file and class name..

**Comment by upchuk** [comment]
Weird, locally still works. And it did work here as well. Need to park this for a moment to unblock a colleague.

**Comment by claudiu-cristea** [comment]
@upchuk & @brummbar this should work. I was confused in the first instance because you said that "locally works". But you've done a manual test locally, you didn't run the test locally.

**Comment by upchuk** [comment]
@claudiu-cristea Actually, I did run the test locally from another repo using this repo in its composer. And the test passed.

**Review by claudiu-cristea — APPROVED** [review]

**Comment by brummbar** [comment]
Found out that the sparql connection was added into the `default.settings.php`, so the tests were getting the connection from there. Thanks for the help @claudiu-cristea .
